### ISSUE TITLE
Add language files in Dutch

### ISSUE THREAD

**Issue by cgiezenberg** [WebberZone/knowledgebase#14]
Hello,

I'm new here on GitHub. But I've made a .po and a .mo file with the translations for this plugin in Dutch. Is it possible to implement them in this plugin? I'll add them in a ZIP-file for you.
[wzkb-nl_NL.zip](https://github.com/WebberZone/knowledgebase/files/666488/wzkb-nl_NL.zip)

When I've uploaded these files in the language file on the server, I don't see any changes. Did I miss out on an action?

Hope to here from you soon.

Kind Regards,

Cynthia

**Comment by ajaydsouza** [comment]
Have you uploaded these in the languages folder of the plugin?
