### ISSUE TITLE
Width of search box too big.

### ISSUE THREAD

**Issue by Colinsp** [WebberZone/knowledgebase#15]
You currently have the width of the search box set in your CSS as 100% and you have then added a margin to this div. As a result the search box goes outside the page width on the right side and causes a horizontal scroll bar on sites. Change the width to ~95% so the definition should be
`.wzkb-search-form {
  border: 1px solid #ddd;
  font-size: 1.3em;
  margin: 20px 0;
  padding-left: 10px;
  padding-right: 12px;
  position: relative;
  width: 95%;
}`

**Comment by ajaydsouza** [comment]
Thanks. I'll give this a test to see how it works

**Comment by ajaydsouza** [comment]
https://github.com/WebberZone/knowledgebase/commit/f1f851a98e94d7e013a32a59798457c8af918432
