### ISSUE TITLE
Set number of columns - Enhancement

### ISSUE THREAD

**Issue by Colinsp** [WebberZone/knowledgebase#16]
Would it be possible to enhance the plugin with the option for the user to set the number of columns to display? On a site of say 1200px width there is sufficient space for about 4 categories if there is no sidebar display.

**Comment by ajaydsouza** [comment]
Can't this be handled by overriding the code with you own CSS?

**Comment by Colinsp** [comment]
Possibly but there is no documentation on what css classes need to be defined that I have been able to find

**Comment by ajaydsouza** [comment]
That's something I need to find the time to work to update.
The styles are all in here: https://github.com/WebberZone/knowledgebase/blob/master/public/css/styles.css

Also, you can see the HTML markup of this: https://webberzone.com/support/knowledgebase/

I do notice what you might mean on number of columns for the above I only have a single column for my categories when I should have two ideally. Need to do more tweaking on the CSS...

I'm more than happy to incorporate your CSS suggestions to get these fixed. If you're comfortable either post it here or send me pull requests if that's easier.

**Comment by Colinsp** [comment]
Thanks for those links I will take a look. 
I am not too familiar with pull requests so I will work on your existing CSS file and post the changes back here in a comment.

**Comment by Colinsp** [comment]
I have made the changes to the CSS and commented them where I have made them. I have altered the search box width so that it fits properly on small screened devices to prevent horizontal scroll bars.

[KB-css.txt](https://github.com/WebberZone/knowledgebase/files/801177/KB-css.txt)

**Comment by ajaydsouza** [comment]
Thank you. I will give this a shot on my install as well. Need to actively work on the documentation of this plugin too.

**Comment by Colinsp** [comment]
It would be great to add more of the responsive grid definitions to the CSS and to have the number of columns as an option on the settings page but appreciate that this may be too much work.

**Comment by ajaydsouza** [comment]
That can be done. In terms of CSS, what exactly do you have in mind?

**Comment by Colinsp** [comment]
As far as the CSS is concerned add the 3, 4 and possibly 5 column CSS from the Responsive Grid site and then have an option in setting for the user to select the number of top level and sub level columns rather than just the current CSS that is only for 2 columns.
