### ISSUE TITLE
My knowledgebase broken css

### ISSUE THREAD

**Issue by silu44** [WebberZone/knowledgebase#2]
why my knowledgebase  appear in vertical view ?

category1 
category1 
.category1 
category1  

not   

category1  category1  category1  category1  
category1  category1  category1  category1 

any suggestions ?

**Comment by ajaydsouza** [comment]
What's your site URL for me to see?

**Comment by silu44** [comment]
i solved it by creating sub category thanks , my site was local

**Comment by ajaydsouza** [comment]
Thanks for confirming.
