### ISSUE TITLE
2 column graphical bug for second row and + 

### ISSUE THREAD

**Issue by ghost** [WebberZone/knowledgebase#21]
in public/css/styles.css line 78

```
.col:first-child {
	margin-left:0;
}
```

Only apply to the first element, but for a 2 column display it should apply to every 2 elements. 

This : http://imgur.com/PdNjqya

should look like this: http://imgur.com/IMl8Ufa

**Comment by ajaydsouza** [comment]
Thanks. I will implement this in the next version

**Comment by ajaydsouza** [comment]
@border0464111 
Do you still have this issue in the latest version of the plugin? I'm not able to replicate this issue or add a fix to this as a result.
