### ISSUE TITLE
Markdown didn't work on pages under knowledgebase

### ISSUE THREAD

**Issue by Jeffrey9130** [WebberZone/knowledgebase#35]
Hi,
As said in the title, all markdown codes, with WP markdown, didn't work in knowledge base pages.

**Comment by Jeffrey9130** [comment]
In default, the WP markdown would work on all pages I think. It should be loaded at an early stage and translate all markdown symbols into html counterpart.
More details are here: https://wordpress.org/plugins/wp-markdown/

I short, I guess the pages under KB group didn't load all plug-ins.

**Comment by Jeffrey9130** [comment]
I just found markdown works on preview page but not on posted page.

**Comment by ajaydsouza** [comment]
I will run a check with the plugin when I have time but I can't seen what I can do to make it work as the Knowledge base posts are simply custom post types so in theory should work.
